version: '3.9'
services:
  mysql:
    image: 'mysql:latest'
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - 'MYSQL_DATABASE=wms_db'
      - 'MYSQL_ROOT_PASSWORD=root'
    ports:
      - '3308:3306'
    volumes:
      - db_data:/var/lib/mysql
volumes:
      db_data:
